### ISSUE TITLE
Error in Ruby Credentials documentation. 

### ISSUE THREAD

**Issue by prdanelli** [googleapis/google-cloud-ruby#11424]
Hello, 

Your documentation states that for `PubSub` credentials, you accept a "Path to JSON file, or JSON contents". 

https://googleapis.dev/ruby/google-cloud-pubsub/latest/file.AUTHENTICATION.html#environment-variables

However, a JSON string is not accepted by the `Credentials` class, which instead requires a `Hash` object to be passed in. 

https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud/credentials.rb#L54

So, the following is actually required to avoid seeing an error: 

```
Google::Cloud::PubSub.configure do |config|
    config.project_id  = "project_id"
    config.credentials = JSON.parse(ENV["PUBSUB_KEYFILE"])
end
```

**Comment by quartzmo** [comment]
@prdanelli Thanks for reporting this issue!

**Comment by prdanelli** [comment]
Thanks for the time you all put into these Gems.

**Comment by quartzmo** [comment]
I reproduced this, but with some observations regarding the issue description above.

1. The example given above, which I reproduce below, demonstrates setting the credentials via `configure` -- not via environment variables. However, the docs quoted above ("Path to JSON file, or JSON contents") are from the section on environment variables. The code demonstration should use environment variables rather than `configure`.
2. The code link above is to [`Google::Cloud::Credentials`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud/credentials.rb), but the actual superclass used by google-cloud-pubsub is [`Google::Auth::Credentials`](https://github.com/googleapis/google-auth-library-ruby/blob/master/lib/googleauth/credentials.rb), as seen in the backtrace below.

```
irb(main):002:0>  json = "{\n  \"type\": \"service_account\",\n  \"project_id\": ... }"
irb(main):003:1* Google::Cloud::PubSub.configure do |config|
irb(main):004:1*   config.project_id  = "my-project-id"
irb(main):005:1*   config.credentials = json
irb(main):006:0> end
irb(main):011:0> Google::Cloud::PubSub.new
/Users/quartzmo/.rbenv/versions/3.0.1/gemsets/quartzmo/gems/googleauth-0.16.2/lib/googleauth/credentials.rb:495:in `verify_keyfile_exists!': The keyfile '{ (RuntimeError)
  "type": "service_account",
  "project_id": ...
}
' is not a valid file.
	from /Users/quartzmo/.rbenv/versions/3.0.1/gemsets/quartzmo/gems/googleauth-0.16.2/lib/googleauth/credentials.rb:551:in `update_from_filepath'
	from /Users/quartzmo/.rbenv/versions/3.0.1/gemsets/quartzmo/gems/googleauth-0.16.2/lib/googleauth/credentials.rb:378:in `initialize'
	from /Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-pubsub/lib/google/cloud/pubsub.rb:100:in `new'
```

I will attempt to reproduce the error using environment variables rather than `configure`.

**Comment by quartzmo** [comment]
I could not reproduce the error when setting the contents of my keyfile in one of the environment variables listed in [AUTHENTICATION.html#environment-variables](https://googleapis.dev/ruby/google-cloud-pubsub/latest/file.AUTHENTICATION.html#environment-variables). I observed that `Google::Auth::Credentials` [correctly parses the JSON string in the variable](https://github.com/googleapis/google-auth-library-ruby/blob/master/lib/googleauth/credentials.rb#L431).

**Comment by quartzmo** [comment]
The [AUTHENTICATION.html#credentials](https://googleapis.dev/ruby/google-cloud-pubsub/latest/file.AUTHENTICATION.html#credentials) section states:

> The Project ID and Credentials JSON can be configured instead of placing them in environment variables or providing them as arguments.

This seems misleading, so I propose changing it to:

> The Project ID and path to the Credentials JSON file can be configured instead of placing them in environment variables or providing them as arguments.

**Comment by 9mm** [comment]
Holy cow this was frustrating, thank god I found this I would have been stuck forever
