### ISSUE TITLE
cloudrad: normalize method names in modules

### ISSUE THREAD

**Issue by TheRoyalTnetennba** [googleapis/google-cloud-ruby#13976]
currently module method names are treated as links (to themselves), correct this to match class/instance methods.

**Comment by dazuma** [comment]
DocFX has assumptions about modules and classes. One of those is that all the content in modules are links to external items rather than inline in the module. So the module method is a link to itself. We want to get rid of the link. The way to do this is to set isEmbedded to true for these objects.

Maybe start somewhere here: https://github.com/googleapis/doc-templates/blob/a0cf33c2cb9c278bb04a05e965d81ec1029fd4f8/third_party/docfx/templates/devsite/UniversalReference.common.js#L28

We did this for consts here: https://github.com/googleapis/doc-templates/blame/a0cf33c2cb9c278bb04a05e965d81ec1029fd4f8/third_party/docfx/templates/devsite/UniversalReference.common.js#L371

We can't blanket set isEmbedded because it might break other languages that have a different idea of what a module is. Have to be careful about doing things specifically for Ruby.
