### ISSUE TITLE
[google-cloud-pubsub] The client-level timeout setting does not appear to take effect

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#14050]
We got a customer report that the "timeout" configuration for `Google::Cloud::Pubsub` is not having any effect. Example code:

```ruby
client = Google::Cloud::PubSub.new(timeout: 5)
```

Making requests using that client still appear to use the default timeout (normally 60s for most calls).

The following also does not seem to work:

```ruby
Google::Cloud::PubSub.configure do |config|
  config.timeout = 5
end
```

A manual trace through the code suggests that the default _RPC-specific_ timeout set in the GAPIC client is taking precedence over a customized user-provided _global_ timeout. It's possible this should be the other way around (but I'm not 100% convinced yet.) If not, we should at minimum have a documented way to set custom RPC-specific timeouts from the veneer layer.

This probably is not limited to PubSub; likely it affects other veneers, and indeed probably most GAPICs. A long-term solution might require work in the generator and/or gapic-common.

**Comment by dazuma** [comment]
Assigning to @quartzmo initially to investigate options, as this could interact with the work on #13953.

**Comment by quartzmo** [comment]
I reproduced this in a passing unit test:

```
require "helper"

describe Google::Cloud::PubSub::Service, :publisher, :mock_pubsub do
  let(:topic_name) { "topic-name-goes-here" }
  let(:timeout) { 5 }
  let(:msg) { "new-message-here" }
  let(:encoded_msg) { msg.encode Encoding::ASCII_8BIT }
  let(:messages) { [Google::Cloud::PubSub::V1::PubsubMessage.new(data: encoded_msg)] }
  let(:publish_res) { Google::Cloud::PubSub::V1::PublishResponse.new({ message_ids: ["msg1"] }) }

  it "applies timeout param to RPC CallOptions" do
    service = Google::Cloud::PubSub::Service.new project, :this_channel_is_insecure, timeout: timeout
    _(service.timeout).must_equal timeout # 5

    mock = Minitest::Mock.new
    mock.expect :call_rpc, publish_res do |method, request, options|
      _(options[:options].timeout).must_equal 60 # Not 5
      retry_policy = options[:options].retry_policy
      _(retry_policy.retry_codes).must_equal [10, 1, 13, 8, 2, 14, 4]
      _(retry_policy.initial_delay).must_equal 0.1
      _(retry_policy.multiplier).must_equal 1.3
      _(retry_policy.max_delay).must_equal 60.0
      true
    end
    service.publisher.instance_variable_set :@publisher_stub, mock

    service.publish topic_name, messages

    mock.verify
  end
end
```

**Comment by quartzmo** [comment]
Here is a side-by-side demonstration of setting the timeout in google-cloud-pubsub (which doesn't work), and setting it in google-cloud-pubsub-v1, which does work, respectively:

```rb
  it "does not apply Service#initialize timeout param to #publish RPC CallOptions" do
    service = Google::Cloud::PubSub::Service.new project, :this_channel_is_insecure, timeout: 5
    _(service.timeout).must_equal 5

    mock = Minitest::Mock.new
    mock.expect :call_rpc, publish_res do |method, request, options|
      _(options[:options].timeout).must_equal 60 # Default set in V1::Publisher::Client.configure
      true
    end
    service.publisher.instance_variable_set :@publisher_stub, mock

    service.publish topic_name, messages

    mock.verify
  end

  it "applies V1::Publisher::Client.configure to #publish RPC CallOptions" do
    Google::Cloud::PubSub::V1::Publisher::Client.configure do |config|
      config.rpcs.publish.timeout = 5
    end

    service = Google::Cloud::PubSub::Service.new project, :this_channel_is_insecure

    mock = Minitest::Mock.new
    mock.expect :call_rpc, publish_res do |method, request, options|
      _(options[:options].timeout).must_equal 5
      true
    end
    service.publisher.instance_variable_set :@publisher_stub, mock

    service.publish topic_name, messages

    mock.verify
  end
```

**Comment by quartzmo** [comment]
If the default value is removed from the google-cloud-pubsub-v1 client config, it can then be set successfully in google-cloud-pubsub: 

```rb
  it "applies Service#initialize timeout param to #publish RPC CallOptions when value cleared in V1::Publisher::Client.configure" do
    Google::Cloud::PubSub::V1::Publisher::Client.configure do |config|
      config.rpcs.publish.timeout = nil
    end

    service = Google::Cloud::PubSub::Service.new project, :this_channel_is_insecure, timeout: 5

    mock = Minitest::Mock.new
    mock.expect :call_rpc, publish_res do |method, request, options|
      _(options[:options].timeout).must_equal 5
      true
    end
    service.publisher.instance_variable_set :@publisher_stub, mock

    service.publish topic_name, messages

    mock.verify
  end
```

**Comment by quartzmo** [comment]
Above tests are available in [this branch](https://github.com/quartzmo/google-cloud-ruby/blob/pubsub-v1-config-test/google-cloud-pubsub/test/google/cloud/pubsub/service_v1_client_test.rb).

**Comment by quartzmo** [comment]
In googleapis/python-pubsub, the precedence of timeout (and retry) configuration works differently. Much thanks to @tseaver for explaining this to me!

1. If the user does not provide any timeout configuration, [the service config default is used](https://github.com/googleapis/python-pubsub/blob/2ad639d6370c7a085498595d7bd0d7eaadfff3c1/google/cloud/pubsub_v1/types.py#L110).
1. If the user provides only [client-scope timeout configuration](https://github.com/googleapis/python-pubsub/blob/2ad639d6370c7a085498595d7bd0d7eaadfff3c1/google/cloud/pubsub_v1/publisher/client.py#L68-L70), it [is used](https://github.com/googleapis/python-pubsub/blob/2ad639d6370c7a085498595d7bd0d7eaadfff3c1/google/cloud/pubsub_v1/publisher/client.py#L350) instead of the service config default.
1. If the user provides only [method-call-scope timeout configuration](https://github.com/googleapis/python-pubsub/blob/2ad639d6370c7a085498595d7bd0d7eaadfff3c1/google/cloud/pubsub_v1/publisher/client.py#L280-L282), it [is used](https://github.com/googleapis/python-pubsub/blob/2ad639d6370c7a085498595d7bd0d7eaadfff3c1/google/cloud/pubsub_v1/publisher/client.py#L349-L350) instead of the service config default.
1. If the user provides both client-scope and method-call-scope timeout configuration, the method-call-scope [is used](https://github.com/googleapis/python-pubsub/blob/2ad639d6370c7a085498595d7bd0d7eaadfff3c1/google/cloud/pubsub_v1/publisher/client.py#L349-L350) instead of the client-scope and the service config default.

Detail note from @tseaver:

> `gapic_v1.method.DEFAULT` is a marker object which normally means, "fall
back to the service config value".  The Pub/Sub veneer client uses it in
its `publish` method to mean, "fall back to the one in
`publisher_options`, which may itself be `gapic_v1.method.DEFAULT`.
That value is then passed to the generated client, which looks for
`gapic_v1.method.DEFAULT` as a sign to apply the service config
defaults:  those defaults are stored in method wrappers in the generated
client's `_wrapped_methods` mapping.

> Python doesn't provide a public way for application code to override the
defaults for individual RPCs, as generated in code from the service
configuration.

**Comment by quartzmo** [comment]
In the generated Ruby client (google-cloud-ruby/google-cloud-pubsub-v1), the precedence of timeout (and retry) configuration works as follows:

1. If the user does not provide any timeout configuration, the [service config default is used](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L58-L114) by [applying rpc-scope defaults](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L424-L426) to the method-call-scope config object [`CallOptions`](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-common/lib/gapic/call_options.rb#L64-L68).
1. If the user provides only [client-scope timeout configuration](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L115), it [is NOT used](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L428-L430) instead of the service config default. This is because the rpc-scope defaults were applied in the [previous statement](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L424-L426) and [`CallOptions#apply_defaults`](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-common/lib/gapic/call_options.rb#L65) does not update `timeout` once it is no longer `nil`.
1. If the user provides only [rpc-scope timeout configuration](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L115), it [is used](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L424-L426) instead of the service config default. This is because the rpc-scope defaults overwrote the config object in the yielded block.
1. If the user provides only [method-call-scope timeout configuration](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L379-L380), it [is used](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub-v1/lib/google/cloud/pubsub/v1/publisher/client.rb#L432) instead of the service config default. This is because [`CallOptions#apply_defaults`](https://github.com/googleapis/gapic-generator-ruby/blob/master/gapic-common/lib/gapic/call_options.rb#L65) does not update `timeout` once it is no longer `nil`.

In the Ruby client, an rpc-scope value from the service config takes precedence over a client-scope value from the user.

**Comment by quartzmo** [comment]
Per offline discussion, I will attempt to resolve this issue in the handwritten client layer (`google-cloud-pubsub`) without changes to the generated client. A non-null value provided for `timeout` to the handwritten client will be applied to all RPC timeouts in the configuration for the generated client.
