### ISSUE TITLE
google-cloud-translate doesn't translate

### ISSUE THREAD

**Issue by vitalinfo** [googleapis/google-cloud-ruby#14156]
F.e. text
```
Ebshan aktutai birokto bodh kora sha always Bangladesh ar kotha bola sha chola jaba or aikhana bhalo laga na
```

detects correct - as `bn`, but doesn't translate it at all and returns initial text

detect response:
```
<Google::Cloud::Translate::V3::DetectLanguageResponse: languages: [<Google::Cloud::Translate::V3::DetectedLanguage: language_code: "bn", confidence: 1.0>]> 
```

translate response:
```
<Google::Cloud::Translate::V3::TranslateTextResponse: translations: [<Google::Cloud::Translate::V3::Translation: translated_text: "Ebshan aktutai birokto bodh kora sha always Bangladesh ar kotha bola sha chola jaba or aikhana bhalo laga na", model: "", detected_language_code: "bn">], glossary_translations: []> 
```

but in the same time, WEB google translate works correctly 
![image](https://user-images.githubusercontent.com/7523182/136596024-8b5ce746-b1e9-4ffc-a584-9ebd4bb02b5f.png)

  - Ruby version: 3.0.2
  - Gem name and version: 3.2.2

any thoughts ?

Thanks!

**Comment by nicain** [comment]
Hello @vitalinfo, thanks for reaching out.  This is interesting, can you reproduce the mistranslation with any of the other client libraries for different programming languages?

**Comment by aribray** [comment]
Hi! I am checking to see if this is a supported use case. The `translate_text` method was successful when I used the Bengali alphabet rather than romanized Bengali:  

<img width="1090" alt="ruby_translate_text_api_call" src="https://user-images.githubusercontent.com/45905583/150003834-620a98ee-b8b8-4191-aa71-be93f4f16fbd.png">

As this doesn't look like a Ruby client library issue specifically, I suggest that you look into the Translation support options here: https://cloud.google.com/translate/docs/getting-support.

I will let you know if I have any helpful conclusions from my investigation.
