### ISSUE TITLE
question: Sort long method parameter lists alphabetically?

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#16026]
Method parameters in both generated clients (example: [Bigtable::Client#read_rows](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-bigtable-v2/lib/google/cloud/bigtable/v2/bigtable/client.rb#L199-L213)) and the handwritten libraries (example: [Bigtable::ReadOperations#read_rows](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb#L78-L86)) are typically presented in order of importance. However, in very long lists of keyword args (example: [Bigquery::Dataset#query_job](https://github.com/googleapis/google-cloud-ruby/blob/main/google-cloud-bigquery/lib/google/cloud/bigquery/dataset.rb#L1131-L1298)), importance is hard to determine past the first few parameters, and the actual ordering tends to become chronological: new params are simply appended to the end of the list.

Should parameter lists that grow beyond a certain length be sorted alphabetically?

**Comment by dazuma** [comment]
In my opinion, the correct order for parameters is "narrative order", i.e. the order best suited to describe the call as a story, to someone reading the code. I believe the generated libraries already implement this by reusing the ordering in the source protos. Agreed that handwritten code will, over time, devolve to chronological order unless it gets refactored; I don't see any practical way to solve that. In any case, I don't think this issue is bothering the current developers, so I'm going to close it.
