### ISSUE TITLE
Google::Analytics::Admin::V1alpha::ListWebDataStreamsRequest is not working

### ISSUE THREAD

**Issue by bv-hemant** [googleapis/google-cloud-ruby#17227]
The request is not working. 
getting error
Google::Cloud::UnimplementedError : 12:The GRPC target is not implemented on the server, host: analyticsadmin.googleapis.com, method: /google.analytics.admin.v1alpha.AnalyticsAdminService/ListWebDataStreams..

**Comment by Ankk98** [comment]
![image](https://user-images.githubusercontent.com/24476799/150086910-04f0159b-8582-4547-9842-725870b5049f.png)

Google's documentation API explorer also not working for this api.

Seems like some issue at google's end.

**Comment by dazuma** [comment]
Thanks for reporting this! I agree, this looks like it may be a back end issue. If it is still happening for you, please report it via the issue tracker for the Google Analytics back end team. You can find links from this page: https://developers.google.com/analytics/help

Closing this issue here because it doesn't appear to be related to the client library gems.
