### ISSUE TITLE
[ERROR] sidekiq 6.0.1 app [5 of 5 busy] SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello

### ISSUE THREAD

**Issue by NqDyK2** [googleapis/google-cloud-ruby#22559]
Hi everybody! Currently I am facing the error as the title of the issue.

My problem with my ruby project, I import 20 images from a link to save to google cloud storage. I tried running on my localhost with docker on local but all 20 images imported very smoothly. But on the deployment environment - Staging an environment close to production, getting that error with a frequency of about 2 to 3 times on 20 images.

Has anyone come across a case like this? Please help me answer this question!!

Below is the version of the project that I am using: 

- ruby '2.6.7'

- gem 'google-cloud-storage', '1.34.1'

- gem 'google-api-client', '0.53.0'

Thank you and have a nice day.

**Comment by dazuma** [comment]
To start off, please try:

* Update your `google-cloud-storage` gem. Your version, 1.34.1, is more than two years old. The latest version is 1.44.0.
* Remove the `google-api-client` gem. It is obsolete, and is likely interfering with the storage client. (Several years ago, we split up `google-api-client` into separate gems for each API. You should already have the separated-out underlying storage client `google-api-storage_v1` in your bundle because it's a dependency of `google-cloud-storage`. However, the obsolete `google-api-client` may have older versions of the storage classes that are overriding the storage client and causing issues.)
* Ruby 2.6 is obsolete and has been for almost a year and a half. It might have bugs or security issues that will not be fixed. I recommend upgrading to a newer version of Ruby (the latest is 3.2.2.).

If you are still having problems after this:

* I recommend contacting your cloud support contact if you have a Google Cloud support plan, or if not, asking on StackOverflow. This repository isn't a support line, and we don't have support engineers here; you'll probably get better help elsewhere.
* The error you're reporting seems like it would be sensitive to the environment (e.g. what operating system you're running, what kind of hosting you're on, any idiosyncrasies of the networking setup, etc.). It would be helpful to provide as much of that kind of information as possible.
* It also might be good to try to narrow your problem to a small code snippet and post it. It would be very difficult to reproduce your problem with the information currently provided.

**Comment by NqDyK2** [comment]
LGTM!!! Thanks for the support I will try to follow your support. If you have any other problems, I hope you can help me. 
/
