### ISSUE TITLE
Create Intent API issue: TypeError: wrong argument type Symbol

### ISSUE THREAD

**Issue by joamaral** [googleapis/google-cloud-ruby#2839]
Hello all, I'm getting an error while trying to create an Intent through the API with a custom payload:

> TypeError: wrong argument type Symbol 
from lib/google/cloud/dialogflow/v2/intents_client.rb:465

The code I'm using is the following:

```
dialogflow_api_request.create_intent("projects/#{params[:agent_id]}/agent", {
display_name: params[:display_name],
        training_phrases: training_phrases,
        messages: [
          {
            payload: {
              fields: {
                test: { string_value: 'foo' }
              }
            }
          }
        ]
      })
```

I don't have a clue why am I getting the error, since I'm able to create an intent providing text as a response instead of a custom payload:
```
text: {
    text: ["foo"]
  }
```

Can you please tell me if this is a gem issue, or if I'm doing something wrong?

Thanks in advance!
João

**Comment by blowmage** [comment]
Using hashes to represent the values will only work so far. The issue you are running into is creating a `Google::Protobuf::Struct` object. The `Google::Protobuf::Struct#fields` attribute is not a Ruby Hash, but a `Google::Protobuf::Map`. `Map` acts like a statically typed `Hash`, and this one requires a `String` key and a `Google::Protobuf::Value` value. So the first error you are getting is because you are passing a `Symbol` instead of a `String`. ( The `test` in `{ test: { string_value: 'foo' } }` is a `Symbol`.)

The second error you are likely to run into is that the value's conversion from a Ruby `Hash` to `Google::Protobuf::Value`.

```ruby
dialogflow_api_request.create_intent(
  "projects/#{params[:agent_id]}/agent", 
  {
    display_name: params[:display_name],
    training_phrases: training_phrases,
    messages: [
      {
        payload: {
          fields: {
            'test' => { string_value: 'foo' }
          }
        }
      }
    ]
  }
)
# raises TypeError: Invalid type Hash to assign to submessage field.
```

To resolve this error you will need to create a `Google::Protobuf::Value` object and pass that in the `fields` hash:

```ruby
dialogflow_api_request.create_intent(
  "projects/#{params[:agent_id]}/agent", 
  {
    display_name: params[:display_name],
    training_phrases: training_phrases,
    messages: [
      {
        payload: {
          fields: {
            'test' => Google::Protobuf::Value.new(string_value: 'foo')
          }
        }
      }
    ]
  }
)
```

**Comment by joamaral** [comment]
@blowmage thank you so much for your help. Understood! One last question: How could I append another hash inside the `fields` hash?

Meaning:

```
payload: {
          fields: {
            'test' => Google::Protobuf::Value.new(string_value: 'foo'),
            'anotherHash' => {
                'test' => Google::Protobuf::Value.new(string_value: 'foo'),
                'another' => Google::Protobuf::Value.new(string_value: 'bar'),
          }
        }
```

I've been trying to do achieve this, and I believe I should use Google::Protobuf::Struct, am I right?
