### ISSUE TITLE
Need to change concurrent-ruby version in gemspec 

### ISSUE THREAD

**Issue by danielmbarlow** [googleapis/google-cloud-ruby#2890]
#### Environment details

  - OS: linux
  - Ruby version: 2.5
  - Gem name and version: 0.15.2 + 0.15.3
  - Rails 5.1.4

#### Code example

Create `test.rb` containing:
```ruby
require "google/cloud/error_reporting"

begin
  fail "Raise an exception for Error Reporting."
rescue => exception
  Google::Cloud::ErrorReporting.report exception
end
```
Run `bin/rails r test.rb`

Result:
```
uninitialized constant Concurrent::Promises (NameError)
```

#### Full backtrace

```sh
from ***/app/vendor/bundle/ruby/2.5.0/gems/google-cloud-error_reporting-0.31.0/lib/google/cloud/error_reporting.rb:230:in `report'
***/app/vendor/bundle/ruby/2.5.0/gems/google-cloud-error_reporting-0.31.0/lib/google/cloud/error_reporting/async_error_reporter.rb:94:in `report': uninitialized constant Concurrent::Promises (NameError)
```

Cause:
`concurrent-ruby` doesn't contain `Concurrent::Promises`:
https://github.com/ruby-concurrency/concurrent-ruby/tree/v1.0.5/lib/concurrent

`v1.1.0` does:
https://github.com/ruby-concurrency/concurrent-ruby/blob/v1.1.0/lib/concurrent/promises.rb

[gemspec](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-error_reporting/google-cloud-error_reporting.gemspec#L26l) contains: `gem.add_dependency "concurrent-ruby", "~> 1.0"`

**Comment by blowmage** [comment]
Thanks for opening this issue, we will get the dependency updated ASAP.

**Comment by jeromedalbert** [comment]
I had a similar issue where I would get `uninitialized constant Concurrent::Promises (NameError)` even though I was using the latest `google-cloud-ruby`.

The problem was that an unrelated gem in my `Gemfile` was requiring an old `1.0.x` version of `concurrent-ruby` when at least `1.1` is needed.

To fix this, I updated my unrelated gem, which allowed `concurrent-ruby` to bump to `1.1.5` and solved the issue.
