### ISSUE TITLE
We can not access the URL currently. Please download the content and pass it in.

### ISSUE THREAD

**Issue by rexhuynh** [googleapis/google-cloud-ruby#2966]
**We are using google-cloud-vision gem and facing this bug**

> A Google::Cloud::DeadlineExceededError occurred in tickets#create_ticket:
> We can not access the URL currently. Please download the content and pass it in.

After i upload Image to S3 i received this bug, but the url is correct. 
It not always happened, out of 20 requests i just got 1 error.
Please, check my issue, thank a lot.

**Comment by blowmage** [comment]
Hi, thanks for the issue. The error you received is from the backend API, not something created as a result of the Ruby client. There is a StackOverflow article about it [here](https://stackoverflow.com/questions/45119587/we-can-not-access-the-url-currently).

The error happened because the backend API was unable to access the image URL provided. To ensure the API gets the image, you can download the image file and pass it to the API instead of using a URL. I would look at rescuing this API error when using a URL and download and pass in the image file as a retry.

Unfortunately, this repo is specific to the Ruby client and we are unable to provide API-level support. The [vision support page](https://cloud.google.com/vision/docs/support) lists various ways to contact the Vision API team for support, including support tickets.

**Comment by rexhuynh** [comment]
Hi @blowmage  thank you for reply. 
It quite weird, i can make sure the url always exist because i  have checked many time and seem like not only me facing this issue.
[https://github.com/googleapis/google-cloud-java/issues/2276#issuecomment-370898357](url)
And this is my code.
<img width="903" alt="screen shot 2019-03-01 at 12 52 13 pm" src="https://user-images.githubusercontent.com/13968562/53619250-39a1c080-3c21-11e9-8335-ee2d1e575f78.png">

**Comment by blowmage** [comment]
I don't know what the cause is, but I am confident is does not originate with the Ruby client. I don't see your code accessing the URL, but even accessing the URL successfully from your network is no guarantee that the Vision API can access it from its network. That is why the error message is suggesting to send the URL contents directly.
