### ISSUE TITLE
Spanner: Adjust timeouts for CreateDatabase and retries for other methods

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-cloud-ruby#3522]
As part of a recent change to GAPIC Configuration, timeouts and retries need to be updated. 

Ensure that the timeouts and retires specified in https://github.com/googleapis/googleapis/commit/cc233544aa39b8947c9b929819aeb08e2cb71feb#diff-4501db3e3507bcce8496c9aea2017d96 are reflected in this client library.

**Comment by quartzmo** [comment]
Yes, these values have all been updated in master since 88454f25dbfa8c0feaf03f0887d66ba8bf341d19 (see below), but they haven't been released yet. I'll create a release PR now.

1. [Database Admin - CreateDatabase](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json#L29)

1. [Database Admin - UpdateDatabaseDdl](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json#L39)

1. [Database Admin - DropDatabase](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/admin/database/v1/database_admin_client_config.json#L44)

1. [Spanner - default](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json#L15)

1. [Spanner - streaming](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json#L24)

1. [Spanner - long_running](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json#L33)

1. [Spanner - ListSessions](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-spanner/lib/google/cloud/spanner/v1/spanner_client_config.json#L54)
