### ISSUE TITLE
Table#read_rows Enumerator should stop after InvalidRowStateError

### ISSUE THREAD

**Issue by quartzmo** [googleapis/google-cloud-ruby#3596]
When receiving an `Enumerator` from `Table#read_rows`, users call `Enumerator#next` to get each row. If the enumerator raises `InvalidRowStateError`, subsequent calls to `next` attempt to recall the RPC (see unit test result below). Instead, the enumerator should raise `StopIteration` for subsequent calls.

```
ReadRowsTest#test_0: invalid - no commit [/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/test/google/cloud/bigtable/conformance_test.rb:88]:
[StopIteration] exception expected, not
Class: <MockExpectationError>
Message: <"No more expects available for :read_rows: [\"projects/test/instances/test-instance/tables/test-table\", {:rows=><Google::Bigtable::V2::RowSet: row_keys: [], row_ranges: []>, :filter=>nil, :rows_limit=>nil, :app_profile_id=>nil}]">
---Backtrace---
/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/rows_reader.rb:80:in `read'
/Users/quartzmo/code/google/codez/google-cloud-ruby/google-cloud-bigtable/lib/google/cloud/bigtable/read_operations.rb:173:in `read_rows'
/Users/quartzmo/.rbenv/versions/2.4.5/gemsets/quartzmo/gems/rake-12.3.2/lib/rake/rake_test_loader.rb:1:in `each'

```

**Comment by quartzmo** [comment]
See [discussion on conformance tests PR](https://github.com/googleapis/google-cloud-ruby/pull/3584#discussion_r300043187)

**Comment by blowmage** [comment]
When a Ruby Enumerator raises when `#next` is called, it will restart the iteration. This means that the `Table#read_rows` method will be called again with the original arguments. This is different than an Enumerator created from a fixed list, like an array:

```ruby
enum = [0, 1, 2].to_enum
enum.next #=> 0
enum.next #=> 1
enum.next #=> 2
enum.next # StopIteration (iteration reached an end)

enum.next # StopIteration (iteration reached an end)
```

When a non-fixed Enumerator is created, and an error is raised, the Enumerator starts over. This means we are unable to ensure that the Enumerable can be stopped.

```ruby
enum = [0, 1, StandardError, 2].lazy.map do |x|
  raise x if x.is_a? Class
  x
end
enum.next #=> 0
enum.next #=> 1
enum.next # StandardError (StandardError)

enum.next #=> 0
enum.next #=> 1
enum.next # StandardError (StandardError)
```

Therefore, I don't think this can be "fixed", it is just how Ruby behaves. Most users will iterate the Enumerator, instead of calling `Enumerator#next`, so I don't think many will bump into this. And if they do, this is the same behavior for all Enumerators everywhere.
