### ISSUE TITLE
[datastore] Support overriding endpoint host

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-cloud-ruby#3753]
Support overriding the endpoint host in the veneer layer, by setting either constructor argument or config field.

See #3752 for an example from bigtable.

**Comment by quartzmo** [comment]
@dazuma @blowmage `Google::Cloud::Datastore.new` [already passes `emulator_host` as `host` to `Service.new`](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-datastore/lib/google/cloud/datastore.rb#L116). This is also true for [firestore](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-firestore/lib/google/cloud/firestore.rb#L90). Do we want to keep these existing "host" params as aliases, or should we deprecate them in favor of `endpoint`? @blowmage left `emulator_host` alone in Pub/Sub in #3723, but I think it's worth discussing because of user potential confusion about whether they are the same or different.

**Comment by quartzmo** [comment]
Regarding my `emulator_host` question above, I see now that the behavior is not the same due to the handling of credentials, so both parameters are needed. Please disregard, thanks.
