### ISSUE TITLE
Using query parameters in detect intent request

### ISSUE THREAD

**Issue by stedied** [googleapis/google-cloud-ruby#4027]
Hello everyone,

I'm trying to pass some query parameters with a detect intent, however, receive an ArgumentError (unknown keywords: time_zone, geo_location, contexts, reset_contexts, session_entity_types, payload).

If I send the request without the query_params, everything works fine. Do you know what I do wrong?

The source code is:

  text_input = Google::Cloud::Dialogflow::V2::TextInput.new
  text_input.text = "test request"
  text_input.language_code = "de"

  query_input = Google::Cloud::Dialogflow::V2::QueryInput.new
  query_input.text = text_input   
  query_params = Google::Cloud::Dialogflow::V2::QueryParameters.new

   response = session_client.detect_intent(session=session, query_input = query_input, query_params = query_params)

Thank you very much in advance for your support.

**Comment by blowmage** [comment]
Hi @stedied, thanks for the question. If you look at [the `detect_intent` method signature](http://googleapis.dev/ruby/google-cloud-dialogflow/v0.6.0/Google/Cloud/Dialogflow/V2/SessionsClient.html#detect_intent-instance_method), `query_params` is a named argument. So instead of passing it as a positional argument, you need to also pass the name.

```ruby
response = session_client.detect_intent(session, query_input, query_params: query_params)
```

Does changing the method signature in your code fix this for you?

**Comment by stedied** [comment]
Hey,

great, this solved it. Thank you a lot for your fast support!
