### ISSUE TITLE
Signed URL: Special Chars in file name not handled properly in V4 version

### ISSUE THREAD

**Issue by chvreddy** [googleapis/google-cloud-ruby#7835]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: MAC
  - Ruby version: ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin19]
  - Gem name and version: gem 'google-cloud-storage', '1.27.0'

#### Steps to reproduce

  1. ...
#### Code example

```ruby
gcs_object.signed_url( method: "GET", expires: 5 * 60, issuer: issuer, signer: signer, version: :v4 )

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: bucket_name/folder1/id,+firstn,+lastn/image1.jpeg</Details>
</Error>
```

With V4 unable to convert special char + to '%20 hence getting above error.

#### Code example

```ruby
gcs_object.signed_url( method: "GET", expires: 5 * 60, issuer: issuer, signer: signer, version: :v2 )

```

When using version V2, Able to download the image.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by quartzmo** [comment]
Can you try upgrading to version `1.29.0`? It includes [this fix](https://github.com/googleapis/google-cloud-ruby/commit/2180747bda834aa7942c8939b13f21223f2cff8c) provided by @cfactolerin.

**Comment by chvreddy** [comment]
upgraded to gem 'google-cloud-storage', '1.29.0'
Still same issue

**Comment by cfactolerin** [comment]
Hi @quartzmo I think my fix did not include this unfortunately. What i fixed was only the query params when we wanted to have a different file name during downloading of the file. I saw another CGI.escape [here](https://github.com/googleapis/google-cloud-ruby/blob/d1319cba5592842a51295c6c07670171546d9e88/google-cloud-storage/lib/google/cloud/storage/file/signer_v4.rb#L290). 

This however might involve business decisions already because this means that before signer v4, cloud storage is allowing spaces on the file names. Now, the file path actually includes + instead.

**Comment by quartzmo** [comment]
@chvreddy Thank you for reporting this bug. It looks like the path in `v4` should use `%20` for spaces, so I expect I will be able to publish a fix. I'm currently requesting an update to the shared conformance tests for this feature in order to specify the behavior in those tests.

**Comment by chvreddy** [comment]
Thanks @quartzmo
